name = "flsh"
type = "javascript"
compatibility_date = "2021-12-23"
workers_dev = false

[site]
bucket = ".output/public"
entry-point = ".output"

[build]
command = "true"
upload.format = "service-worker"

[env.dev]
route = "link.dev.felixoi.com/*"

[env.production]
route = "link.felixoi.com/*"
