name: api-deployment

on:
  push:
    paths:
      - 'api/**'

defaults:
  run:
    working-directory: ./api

jobs:
  ci:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ ubuntu-latest ]
        node: [ 16 ]

    steps:
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}

      - name: Checkout
        uses: actions/checkout@master

      - name: Cache node_modules
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ matrix.os }}-node-v${{ matrix.node }}-deps-${{ hashFiles(format('{0}{1}', github.workspace, '/yarn.lock')) }}

      - name: Install Dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: yarn

      - name: Set dev environment
        if: github.ref == 'refs/heads/dev'
        run: echo "ENVIRONMENT=dev" >> $GITHUB_ENV

      - name: Set production environment
        if: github.ref == 'refs/heads/production'
        run: echo "ENVIRONMENT=production" >> $GITHUB_ENV

      - name: Publish Site to Cloudflare
        uses: carepenny/wrangler-action@2.0.0
        if: (github.ref == 'refs/heads/dev') || (github.ref == 'refs/heads/production')
        with:
          workingDirectory: 'api'
          apiToken: ${{ secrets.CF_API_TOKEN }}
          environment: ${{ env.ENVIRONMENT }}
        env:
          CF_ZONE_ID: ${{ secrets.CF_ZONE_ID }}
          CF_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }}
